### ISSUE TITLE
Add label does not work

### ISSUE THREAD

**Issue by mukherjeer-mms** [buildsville/add-remove-label#6]
Hi, thank you for creating the action, I was excited about using it, as it solves a particular problem I have. Unfortunately I am not able to make it work. The step for add label fails after listing all the env variables.

```
- name: add label
        uses: buildsville/add-remove-label@v2.0.0
        with:
            token: ${{ secrets.PUSH_TOKEN_FOR_GITHUB }}
            labels: deployed-feature
            type: add
```

Output is as follows:

```
Run buildsville/add-remove-label@v2.0.0
  with:
    token: ***
    labels: deployed-feature
    type: add
  env:
    GITHUB_PR_LABEL_DEPLOY_ME: 1
    GITHUB_PR_LABEL_DO_NOT_MERGE: 1
    GITHUB_PR_LABEL_BUILD_APP: 1
    PR_LABELS:  deploy-me do-not-merge build-app 
    COMMIT_SHA: ee739f4058acd6374b
    JAVA_HOME: ***
    GRADLE_BUILD_ACTION_SETUP_COMPLETED: true
    GRADLE_BUILD_ACTION_CACHE_RESTORED: true
    BRANCH_NAME: feature/update_cicd
    RELEASE_NUMBER: 0.0.0
    GITHUB_SHORT_SHA: ***
    RELEASE_IMAGE_TAG: 0.0.0-update-cicd
    CLOUDSDK_AUTH_CREDENTIAL_FILE_OVERRIDE: ***
    GOOGLE_APPLICATION_CREDENTIALS: ***
    GOOGLE_GHA_CREDS_PATH: ***
    GOOGLE_CLOUD_PROJECT: ***
    CLOUDSDK_METRICS_ENVIRONMENT: github-actions-setup-gcloud
    DEPLOYMENT_NAME: ***-update-cicd
    GITOPS_BRANCH: dev
    DEPLOYMENT_NAMESPACE: feature
    DEPLOYMENT_SECRET_NAME: ***
    TERRAFORM_BRANCH: dev
    DNS_RECORD: ***
    DNS_RECORD_IAP: ***
    UPDATE_LOADBALANCING: true
    DEPLOYMENT_GCP_PROJECT: ***
    UPDATE_KUSTOMIZATION: true
    APP_FOLDER: apps/common
Not Found
```
